language: python
python:
    - 2.7
    - 3.4
    - 3.5
services:
    - redis-server
env:
    - DJANGO_VERSION=1.8.19
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.8
    - DJANGO_VERSION=1.11.24
    - DJANGO_VERSION=2.0.13
matrix:
    exclude:
        - python: 2.7
          env: DJANGO_VERSION=2.0.13
install:
    # Install requirements
    - pip install -r requirements.txt
    # Install dev requirements for testing
    - pip install -r dev_requirements.txt
    # Install correct django version
    - pip install Django==$DJANGO_VERSION
    # Install autocompleter
    - pip install -e .
script:
    - python test_project/manage.py test
